### PR TITLE
Loosen compiler requirement to gcc-4.8

### PR DESCRIPTION
**Pull request by gdevenyi**
Testing to see if recent work has fixed <gcc5 errors.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Well this is fun! Somehow, ubuntu bionic packages gcc-4.8, but not gcc-4.9...

**Comment by gdevenyi** [comment]
Can someone kill https://travis-ci.org/ANTsX/ANTs/builds/600777059 please?

**Comment by cookpa** [comment]
Got it

Sent from my iPhone

On Oct 21, 2019, at 11:23 AM, Gabriel A. Devenyi <notifications@github.com<mailto:notifications@github.com>> wrote:


Can someone kill https://travis-ci.org/ANTsX/ANTs/builds/600777059 please?

**Comment by gdevenyi** [comment]
Please cancel https://travis-ci.org/ANTsX/ANTs/builds/600796947

**Comment by cookpa** [comment]
Canceled.

**Comment by gdevenyi** [comment]
And again please: https://travis-ci.org/ANTsX/ANTs/builds/600839422 :)

Seems I can't find a source of gcc-4.9, but it looks like 4.8 passes now :)

**Comment by cookpa** [comment]
I have 4.9.1 here, would you like me to test a build?

**Comment by gdevenyi** [comment]
@cookpa I'm doing a local test here, thanks :) I'm quite annoyed that ubuntu has dropped the ball on packaging gcc though...

**Comment by gdevenyi** [comment]
Local 4.9 build passes.

I'm reaching out to someone I know who does lots of ubuntu backports to see if he can update his gcc back/forward ports so we can test all gccs on bionic.

**Comment by gdevenyi** [comment]
Can someone please cancel https://travis-ci.org/ANTsX/ANTs/builds/600847509

Thanks!

**Comment by gdevenyi** [comment]
Yay travis network timeouts, can someone please restart https://travis-ci.org/ANTsX/ANTs/jobs/600949340

**Comment by cookpa** [comment]
I got it

Sent from my iPhone

On Oct 22, 2019, at 10:32 AM, Gabriel A. Devenyi <notifications@github.com<mailto:notifications@github.com>> wrote:


Yay travis network timeouts, can someone please restart https://travis-ci.org/ANTsX/ANTs/jobs/600949340

**Comment by gdevenyi** [comment]
And a build timeout, a restart here please :) https://travis-ci.org/ANTsX/ANTs/jobs/600949339

**Comment by dorianps** [comment]
Done

**Comment by gdevenyi** [comment]
Okay, so at this point the two remaining failures are a result of a combination of "old GCC + newer clang for assembly on OSX bug" see https://github.com/Homebrew/homebrew-core/issues/4812 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71767

Since GCC has closed the gcc5 branch and didn't backport the fix I don't expect that 4.9 and 5 will ever work, and the clang related bug has never had a single comment since 2016: https://bugs.llvm.org/show_bug.cgi?id=28427

I've downgraded xcode for these versions.

**Comment by gdevenyi** [comment]
Can someone cancel: https://travis-ci.org/ANTsX/ANTs/builds/601829913
and then restart:
https://travis-ci.org/ANTsX/ANTs/jobs/601829927
https://travis-ci.org/ANTsX/ANTs/jobs/601829928

If they're good we're good to merge.

**Comment by cookpa** [comment]
Canceled / restarted

**Comment by gdevenyi** [comment]
two above need a restart please

**Comment by cookpa** [comment]
Done

**Comment by gdevenyi** [comment]
Okay, we're not gonna succeed in GCC<6 on OSX anymore, homebrew needs to be completely rebuilt.

I'm confident that GCC 4.8 on Linux is proof enough.

Please cancel:
https://travis-ci.org/ANTsX/ANTs/builds/602123903
https://travis-ci.org/ANTsX/ANTs/builds/602323279

You can either wait for https://travis-ci.org/ANTsX/ANTs/builds/602450962 to pass again, or merge.

**Comment by cookpa** [comment]
@gdevenyi I canceled those links.

Are you saying GCC must be >= 6 on OS X to compile ANTs, or just that you can't get Travis builds working?

**Comment by dorianps** [comment]
The only two commits I see here make travis changes and a single value switch to allow gcc 4.8. I would merge and go ahead to try the old gcc with ANTsR. Existing gcc users should not be impacted.

**Comment by gdevenyi** [comment]
@cookpa I'm saying two things
1) gcc <6 on modern OSX is broken due to a combination of gcc bugs+clang bugs that are unlikely to ever be fixed
2) gcc testing on travis with older OSX versions cannot be completed because homebrew wants to reinstall everything since old OSX are no longer supported

I think getting testing working/passing with gcc 4.8 on Linux is enough to say we're good for compiler coverage, as ANTs also builds on some very old clang installs.

**Comment by cookpa** [comment]
Got it, thanks.

**Comment by gdevenyi** [comment]
This is ready to merge whenever the changes won't affect the remaining tests.

**Comment by cookpa** [comment]
OK then. Thanks again!

**Pull request merged**
