### PR TITLE
COMP: Install ANTs with the make command

### PR DESCRIPTION
**Pull request by cookpa**
This installs to CMAKE_INSTALL_PREFIX after building, removes need for

cd ANTS-build
make install

### CODE REVIEW

**Comment by cookpa** [comment]
Thoughts? This installs during the superbuild `make`, which is also not completely standard, but I think it would overall cut down on user confusion?

**Comment by gdevenyi** [comment]
Well this is easy, I was hoping to do something about this.

What do the logs look like when you make install?

**Comment by gdevenyi** [comment]
And, have you exercised all combination of BUILD_SHARED_LIBS and use system VTK/ITK settings?

**Comment by cookpa** [comment]
It looks like I was doing it wrong; one should not set `INSTALL_DIR` because that doesn't actually configure anything, it just changes the `<INSTALL_DIR>` token that can be expanded by the external project if it wants.

The important change was to stop setting `INSTALL_COMMAND=""`, because that disables the install step.

https://cmake.org/cmake/help/latest/module/ExternalProject.html

The problem with this approach is that if we want to install to a privileged location, we have to run the whole make with those privileges, and not just `make install`.

**Comment by cookpa** [comment]
Going to close for now, as I need to work on other things. It will take some time to test various combinations of system ITK, shared libs, etc.

**Comment by gdevenyi** [comment]
I have to wrap my head around how the minc-toolkit-v2 superbuild does this, as make and make install work at the top level fine.

**Pull request closed without merging**
