### PR TITLE
Install into appropriate platform directories

### PR DESCRIPTION
**Pull request by TheChymera**
Via `GNUInstallDirs`:

* tested, producing: [ants_files.txt](https://github.com/ANTsX/ANTs/files/3721196/ants_files.txt)
* fixes https://github.com/ANTsX/ANTs/issues/872

@gdevenyi

### CODE REVIEW

**Comment by gdevenyi** [comment]
Thanks @TheChymera this is a good start but it doesn't modify the superbuild codepath we had trouble with in my previous PR. That's the way most people are installing ANTs still.

I think this can be addressed if you could provide some detail on how you got your ITK install to honour this lib vs lib64 setting, since we'll need to do something like that to the ITK and VTK in the superbuild.

**Comment by TheChymera** [comment]
>I think this can be addressed if you could provide some detail on how you got your ITK install to honour this lib vs lib64 setting, since we'll need to do something like that to the ITK and VTK in the superbuild.

This patch was all that was needed (in addition to your logic patch from https://github.com/ANTsX/ANTs/pull/867 --- though it seems unrelated) to successfully produce and install the attached file list. Does this seem unlikely, or is anything missing?

**Comment by gdevenyi** [comment]
As always, the exact cmake configuration determines which things are built and which things are installed. Your file list does not provide suffcient information on whether this patch works. The exact cmake config is also required.

My guess is you are not testing the SuperBuild path since you are specifying USE_SYSTEM_ITK AND USE_SYSTEM_VTK. Most users are using the SuperBuild, which (in the BUILD_SHARED_LIBS config) triggers this codepath:
https://github.com/ANTsX/ANTs/blob/master/ANTS.cmake#L178

Notice that this still hard-codes a libs directory. Please test this codepath using the ANTs-documented installation instructions.

**Comment by TheChymera** [comment]
@gdevenyi could you provide a link to the install instructions you are referring to, I found no unabbiguous resource in the README.

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

**Comment by TheChymera** [comment]
@gdevenyi ok, so I gave it a try and it seems to work:

[build.log](https://github.com/ANTsX/ANTs/files/3772758/build.log)
[install.log](https://github.com/ANTsX/ANTs/files/3772763/install.log)
[mytree.txt](https://github.com/ANTsX/ANTs/files/3772765/mytree.txt)

**Comment by gdevenyi** [comment]
Hi,

The build you logged did not use -DBUILD_SHARED_LIBS so the shared libraries were not installed and so that codepath was not triggered.

This line needs to be updated to conform with the lib vs lib64 detection inside CMAKE
https://github.com/ANTsX/ANTs/blob/master/ANTS.cmake#L178

In addition, the ITK/VTK installs may need to be adjusted so that the staging superbuild install honours lib/lib64, details on the Gentoo ITK/VTK configuration would be helpful here to see how thats handled.

**Comment by cookpa** [comment]
Addressed in #1062

**Pull request closed without merging**
