### PR TITLE
WIP: C++11 modernization

### PR DESCRIPTION
**Pull request by hjmjohnson**
Several more changes will be coming soon.

### CODE REVIEW

**Comment by stnava** [comment]
@muschellij2  FYI - next phase of updates

**Comment by hjmjohnson** [comment]
@stnava @ntustison @muschellij2 @gdevenyi 

This PR is now ready for critical review/testing.  I've exhausted my time to work on it this week 👍 

I turned on as much as I could for building/testing.  When I started 160 tests passed, and 5 failed.  When I finished, 160 test passed, 5 failed.

Hans

**Comment by hjmjohnson** [comment]
PS:  All internal testing was done on Mac, so it would be nice if a linux user had a wack at beating on this.

**Comment by ntustison** [comment]
Thanks a lot for this, Hans.  I'll get to this sometime this week/weekend.

**Comment by hjmjohnson** [comment]
@stnava I know that some of the failing tests are simply because of missing test data.  Keeping a healthy test suite is important for trusting community contributions.  If the tests are no longer meaningful, I'd recommend deleting/removing them.

Thanks for the kind words.
Hans

**Pull request merged**
