### PR TITLE
ENH:  Round 5.

### PR DESCRIPTION
**Pull request by ntustison**

### CODE REVIEW

**Comment by gdevenyi** [comment]
Two hung builds should be restarted:
https://travis-ci.org/ANTsX/ANTs/jobs/603122659
https://travis-ci.org/ANTsX/ANTs/jobs/603122660

**Comment by dorianps** [comment]
Restart done.

**Comment by gdevenyi** [comment]
restart please: https://travis-ci.org/ANTsX/ANTs/jobs/603122681

**Comment by cookpa** [comment]
Got it


On Oct 27, 2019, at 9:28 PM, Gabriel A. Devenyi <notifications@github.com<mailto:notifications@github.com>> wrote:


restart please: https://travis-ci.org/ANTsX/ANTs/jobs/603122681

**Comment by gdevenyi** [comment]
All passing, ready for merge.

**Pull request merged**
