### PR TITLE
BUG:  Address incorrect output in morphological close/open.

### PR DESCRIPTION
**Pull request by ntustison**
https://github.com/ANTsX/ANTs/issues/968

### CODE REVIEW

**Comment by cookpa** [comment]
Does this restore the expected behavior that open and close are identical to the combinations of dilate and erode? 

It looks like it would, as the structuring element is the same.

**Comment by ntustison** [comment]
@cookpa This is expected behavior and probably preferred since it actually uses the open and close ITK filters as opposed to the dilate/erode combination equivalents.  I didn't look at the internals but I wouldn't be surprised if the dedicated filters have implementation optimizations.

**Comment by cookpa** [comment]
I agree it makes sense to use the dedicated filter. I was just thinking it would be good to ensure all the parameter choices are in place to ensure

ImageMath 3 dilate.nii.gz MD input.nii.gz $radius
ImageMath 3 closed.nii.gz ME dilate.nii.gz $radius

gives the same results as

ImageMath 3 closed.nii.gz MC input.nii.gz $radius

It looks like that is the case, but I haven't built the branch to check.

**Comment by ntustison** [comment]
Agreed.  Although if the results weren't the same then I would imagine that would warrant an ITK bug report.

**Pull request merged**
