### PR TITLE
COMP: Fix compilation syntax errors from failed build

### PR DESCRIPTION
**Pull request by hjmjohnson**
A hasty git PR missed adding obvious code syntax fixes.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
Sorry,  autoformatter reformatted everything.  I have to run for the moment, but will make a better PR when I have time later.

**Comment by hjmjohnson** [comment]
The real change here is only a few semi-colons and silly syntax errors..

**Comment by hjmjohnson** [comment]
OK.  This is ready now.  Sorry for committing invalid code previously.

**Comment by ntustison** [comment]
Awesome.  No worries.  Thanks a lot, @hjmjohnson .

**Pull request merged**
