### PR TITLE
Fix ITKv5 spatialobjects update

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Comment by ntustison** [comment]
Thanks again, @hjmjohnson .  I'll merge as soon as the travis builds are green from the previous merge.

**Comment by hjmjohnson** [comment]
Please hold off on this for a bit.  There may be bigger issues regarding the spatial transform fixes.

**Comment by ntustison** [comment]
Okay.  Will do.

**Comment by hjmjohnson** [comment]
@ntustison This should be ready to commit now.

**Comment by ntustison** [comment]
Thanks @hjmjohnson .  Was traveling yesterday.

**Pull request merged**
