### PR TITLE
Switch to using CMAKE_PREFIX_PATH for VTK to account for differences in lib paths

### LINKED ISSUE #466: ANTs not building with ITK and VTK in SuperBuild
I originally posted this in kaczmarj/ANTs-builds#1, but we weren't able to come to a solution as it seems ITK requires VTK for the VTKGlue module, but VTK builds after ITK. Both @gdevenyi and I aren't familiar enough with this to get CMake to fix this up. Has anyone gotten this to work?

### PR DESCRIPTION
**Pull request by gdevenyi**
Attempting to fix #466

### CODE REVIEW

**Comment by ntustison** [comment]
Thanks for this @gdevenyi .  Is it ready to merge?

**Comment by gdevenyi** [comment]
It works for me (tm) but the last fix did too. I'm hoping for some alternative tests on different environments via #466

**Comment by ptsii** [comment]
This is a bit beyond me.  What exactly am I supposed to do to implement this change?  What exactly is supposed to be modified?  Or is it already modified, and I just need to remove the previous trial folders (that bailed on compiling) and redo:
git clone https://github.com/stnava/ANTs.git

Any suggestions would be welcome!

**Comment by gdevenyi** [comment]
@ptsii 	make the changes as outlined here https://github.com/ANTsX/ANTs/pull/748/files to your local copy and try to build again

**Comment by ptsii** [comment]
I tried rm'ing the folder and starting again, but this gave the same error. So either the change didn't work for my system, or I'm supposed to do something specific to incorporate this change...

**Comment by stnava** [comment]
try a clean clone of ants from github

then do:

cd ANTs

git checkout -b gdevenyi-fix-vtk-include mastergit pull
https://github.com/gdevenyi/ANTs.git fix-vtk-include


then try to compile as usual and report back results.

**Comment by ptsii** [comment]
OK, before I saw Brian's suggestion I tried manually editing ANTs/SuperBuild/External_ITKv5.cmake as indicated in https://github.com/ANTsX/ANTs/pull/748/files, then cleaning out my build directory, ccmake and compile, and it worked.  Or at least it got to: 
[100%] Completed 'ANTS'
[100%] Built target ANTS
I haven't tried anything yet, but I assume it wouldn't have gotten that far if something had bailed.  
Thanks for everyone's help!! Gabriel's change seems to have fixed the issue.

**Comment by stnava** [comment]
Great - let's try it and see if anything else comes up.

**Pull request merged**
