### PR TITLE
COMP:  GCC 9 enhanced warnings.

### PR DESCRIPTION
**Pull request by ntustison**
Round 1 for:

https://github.com/ANTsX/ANTs/issues/854

### CODE REVIEW

**Comment by gdevenyi** [comment]
Nice, always happy to see that all those warnings can expose bugs once in a while.

I guess I should redo the clang -Weverything once this is merged.

**Comment by ntustison** [comment]
Not a bug in the original code.  But, yes, it will require more than one round.

**Comment by ntustison** [comment]
@gdevenyi --- when you get a chance, please take a look at the checks which seem to be failing and let me know what you think.  Unfortunately, the failures seem to deal with travis issues as opposed to code issues.

**Comment by gdevenyi** [comment]
This does not appear to be travis failing, although this code does compile locally fine. I may need to ditch ninja for the build system due to it being simply too quiet to hint as to what is going wrong. I suggest when the current round of build is finished you restart and see what that does.

**Comment by gdevenyi** [comment]
I have a PR at https://github.com/ANTsX/ANTs/pull/871 to switch back to make, to see if we can still build in the time allotted and expose more useful outputs.

**Comment by gdevenyi** [comment]
Damn, so switching to make I can't quite get under the 1.5hr mark on Travis. Can you rebase this on #871 to see if we can get some useful output and figure out why the build is failing? It looks like we may have to do this from time to time to isolate failures...

**Comment by gdevenyi** [comment]
Looks like you found something? Trying #875 to improve verbose ninja since make is too slow.

**Comment by gdevenyi** [comment]
It looks like I managed to fix the verbosity of the travis build in #875 

So, *after* that is merged to master:
```
> git checkout master
> git pull master
> git checkout gcc-9-enhanced-warnings-round1
> git rebase -i master
#using your editor, edit the rebase list to "d" aka drop the makefile modification commit
> git push --force
```

**Comment by ntustison** [comment]
Okay @gdevenyi , all the builds pass (after restarting a few of them).  I'm going to go ahead and merge.  Can you recompile to see if some of those warnings persist?  There were just a ton of them and I'm not sure I was able to keep track and get them all.

**Comment by gdevenyi** [comment]
I will provide an update for the clang and gcc enhanced warnings outputs. Thanks!

**Pull request merged**
