### PR TITLE
Use Enum instead of Type

### PR DESCRIPTION
**Pull request by crossmanith**

### CODE REVIEW

**Comment by gdevenyi** [comment]
Builds all fail on ANTs.

Does your update for ITK5.1 require a newer version ITK?

Re: #940, these are not timeouts, these are failures.

**Comment by gdevenyi** [comment]
It would be helpful if you could provide more version information for your "system ITK 5.1"

**Comment by crossmanith** [comment]
My ITK tree has 8d3961 as the most recent commit. I'll update and see if my patch still works.

**Comment by ntustison** [comment]
@crossmanith -- Did you update the ITK git tag [here](https://github.com/ANTsX/ANTs/blob/master/SuperBuild/External_ITKv5.cmake#L154)?

**Comment by crossmanith** [comment]
Commit 21fc5c94b58c00f5db1a8ff4d2a18e2fbeb59014 from 12/29/2019 introduced the Enums, ANTs checks out an earlier ITK version from the end of november. This is why the travis builds are failing.

**Comment by crossmanith** [comment]
I've modified the ITK git tag, set USE_SYSTEM_ITK to OFF and see if it builds successfully

**Comment by ntustison** [comment]
@crossmanith Thanks for checking.

**Comment by crossmanith** [comment]
Do I have to find the earliest ITK commit for a successful build of ANTs or can I take any working commit?

**Comment by ntustison** [comment]
On something like this, we would simply use the most recent commit.

**Comment by gdevenyi** [comment]
Before we merge this, should perhaps we hold on this until there's a need to bump the version again? 

I don't immediately seem any changes in https://github.com/InsightSoftwareConsortium/ITK/compare/49671655c88612fabeb5f0784d3f40123100f166...master that would impact ANTs, except for perhaps https://github.com/InsightSoftwareConsortium/ITK/pull/1557

**Comment by ntustison** [comment]
I would say that this is sufficient reason to bump the ITK version.  We always try to stay current with the latest ITK changes.

**Comment by gdevenyi** [comment]
@crossmanith You can just add the tag change as a new commit on this branch and then git push to update this PR.

**Pull request closed without merging**
