### PR TITLE
Add support for an --interpolation flag in antsMotionCorr

### PR DESCRIPTION
**Pull request by dangom**
Note that no support was added for either Gaussian or genericLabel
interpolation routines, as those require adapting parameters according
to the voxel dimensions. If users want these, they can always fall
back to using antsApplyTransforms for a more generic solution.

### CODE REVIEW

**Comment by dangom** [comment]
Closes #931

Ready for review

**Comment by ntustison** [comment]
Thanks @dangom .  We'll let the travis builds complete and then we'll merge.

**Comment by dangom** [comment]
No prob.
Also worth mentioning that I had to change the short name of --interpolation to -p because -n is already in use by --n-images.

**Comment by ntustison** [comment]
@dangom Thanks again.

**Pull request merged**
