### PR TITLE
DOC: Docker CI badge in README

### PR DESCRIPTION
**Pull request by cookpa**
COMP: Avoid building on draft PR

### CODE REVIEW

**Comment by cookpa** [comment]
Skip CI on draft PRs, now hopefully it will run once I mark it ready

**Comment by cookpa** [comment]
Hmm, nope, looks like I need to do some more work here

**Comment by cookpa** [comment]
Success!

**Comment by ntustison** [comment]
Awesome.  Thanks for this @cookpa

**Comment by dorianps** [comment]
Looking forward if you can do something like this for ANTsR, so I can copy the solution to LINDA, LESYMAP. Great to see a green badge in ANTs.

**Comment by cookpa** [comment]
Should be do-able for ANTsR. I'll have to head over there and merge my Dockerfile PR from ages ago first

**Pull request merged**
