### PR TITLE
BUG:  Need to fill buffer for R and Python interfaces.

### PR DESCRIPTION
**Pull request by ntustison**
https://github.com/ANTsX/ANTsPy/issues/579

### CODE REVIEW

**Comment by stnava** [comment]
my understanding ( from itk discussions ) is the C++ standard does not define expectations for values within uninitialized memory; such values are indeterminate, and accessing them leads to undefined behavior.  ... not sure if itk Allocate is supposed to behave differently though

**Comment by gdevenyi** [comment]
To fix this common issue itk has been transitioning to a single call for both

https://github.com/InsightSoftwareConsortium/ITK/pull/4494

**Comment by cookpa** [comment]
Thanks @gdevenyi - so it looks like we could replace Allocate() with Allocate(true) or, as of that PR, AllocateInitialized() and solve this problem consistently.

**Comment by stnava** [comment]
yes - worthwhile.  would also need to check all the R c++ and python c++ ( not much in the latter , I think ) .... another issue is I have not updated pybind11 in some time .... not sure if this would be related or not.

**Comment by ntustison** [comment]
I'll go ahead and merge this and a future pull can address the more general presence of this issue.

**Comment by ntustison** [comment]
Unless somebody else wants to do it, I can put it on my to-do list to go through and check that the image buffer is initialized.

**Comment by cookpa** [comment]
Thanks Nick, much appreciated. I'll make some issues so we can keep track of this

**Comment by ntustison** [comment]
Thanks @cookpa .  But just to be clear, it might take a couple days to a week.

**Pull request merged**
