### PR TITLE
COMP: Set minimum GCC version 5

### PR DESCRIPTION
**Pull request by cookpa**

### CODE REVIEW

**Comment by gdevenyi** [comment]
Looks like we're touching the same file in #841,

Can I pull the version change in there and depreciate this PR?

**Comment by cookpa** [comment]
Sure go ahead

Sent from my iPhone

On Sep 9, 2019, at 4:48 PM, Gabriel A. Devenyi <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like we're touching the same file in #841<https://github.com/ANTsX/ANTs/pull/841>,

Can I pull the version change in there and depreciate this PR?

**Comment by gdevenyi** [comment]
Great! Can you please kill your travis builds on the other branches and PRs so mine run? :-)

**Comment by cookpa** [comment]
Not easily from my phone. If you sign in to Travis with your GitHub ID, will it let you do stuff?


Sent from my iPhone

On Sep 9, 2019, at 9:06 PM, Gabriel A. Devenyi <notifications@github.com<mailto:notifications@github.com>> wrote:


Great! Can you please kill your travis builds on the other branches and PRs so mine run? :-)

**Comment by ntustison** [comment]
I canceled them.

**Comment by gdevenyi** [comment]
I'm not a member of ANTsX so I don't have any change control available on Travis.

No problem, I'll wait till tomorrow!

**Comment by gdevenyi** [comment]
Oh, thanks @ntustison

**Pull request closed without merging**
