### PR TITLE
Replace DiscreteGaussian with RecursiveGaussian

### LINKED ISSUE #538: SmoothImage produces no output with "large" blur kernel and high resolution image
I found this very odd result which I cannot yet find the origin:
```sh
#1mm Istotropic Image
> SmoothImage 3 mni_icbm152_t1_tal_nlin_sym_09c.nii 16 09c.nii 1 0
WARNING: In /opt/quarantine/ANTs/git/src/build/ITKv4-install/include/ITK-4.12/itkGaussianOperator.hxx, line 61
GaussianOperator (0x7ffc6d0f4a00): Kernel size has exceeded the specified maximum width of 32 and has been truncated to 33 elements.  You can raise the maximum width using the SetMaximumKernelWidth method.
```
Image:
image

```sh
#0.5mm isotropic image
> SmoothImage 3 mni_icbm152_t1_tal_nlin_sym_09b_hires.nii.gz 16 09b.nii 1 0
#No output
```
image

Taking a look over https://github.com/ANTsX/ANTs/blob/master/Examples/SmoothImage.cxx I don't see any place to expect an overflow or other issue, so this may be an ITK bug?

### PR DESCRIPTION
**Pull request by gdevenyi**
Following the merge here: https://github.com/InsightSoftwareConsortium/ITK/commit/569a4701b740d849a1efe20c9fd76a928c645fbb

I've updated the ITK tag to match.

I also rewrote SmoothImage to use RecursiveGaussian instead of DiscreteGaussian, this fixes #538 

This ITK version ID has a bug with HDF5 implementation (breaks MINCIO) so hold on merge until I get get that fixed and I'll update the hash.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Progress on broken HDF5 here:
https://discourse.itk.org/t/updating-itks-hdf5/472/10

**Comment by gdevenyi** [comment]
Now with fixed ITKv5 hash

**Comment by gdevenyi** [comment]
hdf5 "fix" didn't fix MINCIO, still debugging.

**Comment by gdevenyi** [comment]
Build looks okay. Traivs seems to have had a hiccup and hung.

Can someone with rights re-trigger the build?

**Comment by gdevenyi** [comment]
Looks like all is well.

Is this okay for merge now?

**Comment by ntustison** [comment]
Sure.  Thanks for this @gdevenyi .

**Pull request merged**
