### PR TITLE
Clang tidy updates cxx11

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Comment by ntustison** [comment]
This is great @hjmjohnson .  Thanks for all this work.

**Comment by gdevenyi** [comment]
Looks like all the linux gcc builds are failing with these changes.

**Comment by gdevenyi** [comment]
In particular the changes at Examples/antsMotionCorrDiffusionDirection.cxx seem to make gcc unhappy

**Comment by gdevenyi** [comment]
and ANTSIntegrateVelocityField.cxx

**Comment by hjmjohnson** [comment]
Oops.  Sorry, I forgot to hard-code turning on 

`
-DITK_LEGACY_REMOVE:BOOL=OFF # <--- NEEDED TEMPORARILY until fixes for enum-class and ITK 5.1 release are required
`

**Comment by hjmjohnson** [comment]
Wow.  The Travis CI takes a really long time!

**Comment by gdevenyi** [comment]
The previous push you did needed to finish first. In addition, there is an open PR from someone's working branch that keeps getting rebuilt when they work on it which a delaying other builds.

**Comment by cookpa** [comment]
Is it OK if I stop everything but # 1453?

image

**Comment by gdevenyi** [comment]
makes sense to me

**Comment by ntustison** [comment]
Also fine with me.

**Comment by ntustison** [comment]
Also, @hjmjohnson , terribly sorry but I had to push a change to one of your files (``N4BiasFieldCorrection.cxx``) to address a long-standing issue in ANTsR.  If it's easier for you, you can simply merge your changes and I'll update the file afterwards.

**Comment by cookpa** [comment]
OK previous commits and other branches already merged are now canceled, so Travis should now be working on this one.

**Pull request merged**
