### PR TITLE
Type->Enum // added .as_ref() // adjust ITK git tag

### PR DESCRIPTION
**Pull request by crossmanith**

### CODE REVIEW

**Comment by crossmanith** [comment]
Looks like some builds fail due to a time out - how can we avoid that?

**Comment by gdevenyi** [comment]
I'll take a look today

**Comment by gdevenyi** [comment]
We're at the hairy edge of timeout, the build succeeds but we run out of time during the caching.

I've updated the travis config at #946 to ensure that the cache gets populated, which should solve this.

From my perspective, the changes look ok to merge.

**Comment by ntustison** [comment]
Sounds good.  Thanks @crossmanith and @gdevenyi .

**Pull request merged**
