### PR TITLE
ENH: Update for ITKv5 MultiThreader model

### PR DESCRIPTION
**Pull request by hjmjohnson**
Update to utilize the new MultiThreaderBase needed for
setting the number of threads.

### CODE REVIEW

**Comment by ntustison** [comment]
Thanks @hjmjohnson

**Comment by ntustison** [comment]
@hjmjohnson Great.  Thanks.  One question I was going to ask you concerned the new ITK "style"-(I don't know if that's the correct word) change based on, I'm guessing, C++11 standards.  I wrote some new classes ([e.g., simulated displacement fields](https://github.com/ANTsX/ANTs/blob/master/Utilities/itkSimulatedBSplineDisplacementFieldSource.h#L46)) and used this style but I'm wondering about changing existing classes.  Is there a script to make these changes or do we need to go in by hand and do it?

**Comment by hjmjohnson** [comment]
Nick,

 

https://github.com/InsightSoftwareConsortium/ITK/tree/master/Utilities/ITKv5Preparation

 

I’ve got the infrastructure set up to do this already!  If you don’t mind, I’ll take a first pass. 

 

Hans

**Comment by ntustison** [comment]
Awesome.  Thanks for the info and for doing the conversion.  This is great.

**Pull request merged**
