### PR TITLE
Fix ThresholdImage

### PR DESCRIPTION
**Pull request by gdevenyi**
Fixes bug noted at #828

### CODE REVIEW

**Comment by cookpa** [comment]
Looks good thank you

**Comment by ntustison** [comment]
Thanks @gdevenyi .  However, just saw [this](https://github.com/ANTsX/ANTs/pull/837/commits/0f8d4ac7a923f263d5bf20e1f9675b33370ef30e#diff-5003d0db4237942a8abedf7385c00837L81-L84) which isn't obvious behavior and bypasses the [internal check](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/Thresholding/include/itkThresholdImageFilter.hxx#L80-L84) in the filter.  Unless there are good reasons for including this, I would vote to remove it.

**Comment by gdevenyi** [comment]
Okay, will remove completely, I was simply maintaining the existing setup, additional PR incoming.

**Comment by gdevenyi** [comment]
PR #839

**Comment by ntustison** [comment]
I figured.  But thanks for fixing it.

**Pull request merged**
