### PR TITLE
Update travis

### PR DESCRIPTION
**Pull request by gdevenyi**

### CODE REVIEW

**Comment by gdevenyi** [comment]
Attempt to address timeout in #946

**Comment by cookpa** [comment]
Does this need restarting?

**Comment by gdevenyi** [comment]
We're still bumping up again 1h 30min max. I need to cut another 5 min off the timeout wrapper so that cache updating succeeds. Will force-push a change to trigger a restart.

**Comment by gdevenyi** [comment]
Looking good here to avoid timeouts and populating the cache.

**Comment by cookpa** [comment]
Thanks

**Pull request merged**
