### PR TITLE
Convert cmake to use ninja build system in travis for improved build performance

### PR DESCRIPTION
**Pull request by gdevenyi**
Hoping this may fix the timeouts.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Hurrah, it looks like switching in Ninja saves ~20 minutes of build time. Hopefully this will be enough to rescue all the builds that are just over the limit.

**Comment by gdevenyi** [comment]
Again, the only failures we see here are travis connectivity issues failing to download the ExternalData, builds and tests pass, and are faster.

**Comment by gdevenyi** [comment]
We're all good for a merge here. My next project will be figuring out how to cache the ExternalData components so that these random HTTP errors stop breaking the build.

**Comment by ntustison** [comment]
@gdevenyi Thanks for this.

**Pull request merged**
