### PR TITLE
COMP: Adding a CMake option to include the git hash when not building…

### PR DESCRIPTION
**Pull request by cookpa**
… from a repo

  cmake ... -DANTS_SNAPSHOT_HASH=commitsha

then version info will be "snapshot-commitsha"

### CODE REVIEW

**Comment by cookpa** [comment]
@stnava I don't want to break ANTsR again but I thought it would be nice to have the ability to add the commit hash manually when building from a snapshot.

**Comment by gdevenyi** [comment]
Looks good to me.

**Comment by cookpa** [comment]
Travis failures look to be time related, but anyway I am holding off on merging right now so I can try to fix some warnings related to version info

**Comment by gdevenyi** [comment]
Indeed they do, could you try individually restarting the failed ones?

**Comment by cookpa** [comment]
Sure, I'm going to push another commit then I will do that.

I am trying to fix `ANTS.cmake` so that it defines the version variables as 0 if they are not set to a real value. These lines were recently added to `ANTsVersionConfig.h.in`

https://github.com/ANTsX/ANTs/blob/b8889562341471dbe18b415d2bcefb9b8f12232a/ANTsVersionConfig.h.in#L25-L34

to ensure that the version numbers are not null, which broke ANTsR. But it leads to these warnings:

```
In file included from /Users/pcook/tmp/NOT_BACKED_UP/ANTs-b8889562341471dbe18b415d2bcefb9b8f12232a/Examples/ANTsVersion.cxx:19:
/Users/pcook/tmp/NOT_BACKED_UP/antsBuild2/ANTS-build/ANTsVersionConfig.h:30:9: warning: 'ANTS_VERSION_MAJOR' macro redefined [-Wmacro-redefined]
#define ANTS_VERSION_MAJOR 0
        ^
/Users/pcook/tmp/NOT_BACKED_UP/antsBuild2/ANTS-build/ANTsVersionConfig.h:19:9: note: previous definition is here
#define ANTS_VERSION_MAJOR 
        ^
/Users/pcook/tmp/NOT_BACKED_UP/antsBuild2/ANTS-build/ANTsVersionConfig.h:31:9: warning: 'ANTS_VERSION_MINOR' macro redefined [-Wmacro-redefined]
#define ANTS_VERSION_MINOR 0
        ^
/Users/pcook/tmp/NOT_BACKED_UP/antsBuild2/ANTS-build/ANTsVersionConfig.h:20:9: note: previous definition is here
#define ANTS_VERSION_MINOR 
        ^
/Users/pcook/tmp/NOT_BACKED_UP/antsBuild2/ANTS-build/ANTsVersionConfig.h:32:9: warning: 'ANTS_VERSION_PATCH' macro redefined [-Wmacro-redefined]
#define ANTS_VERSION_PATCH 0
        ^
/Users/pcook/tmp/NOT_BACKED_UP/antsBuild2/ANTS-build/ANTsVersionConfig.h:21:9: note: previous definition is here
#define ANTS_VERSION_PATCH 
        ^
/Users/pcook/tmp/NOT_BACKED_UP/antsBuild2/ANTS-build/ANTsVersionConfig.h:33:9: warning: 'ANTS_VERSION_TWEAK' macro redefined [-Wmacro-redefined]
#define ANTS_VERSION_TWEAK 0
        ^
/Users/pcook/tmp/NOT_BACKED_UP/antsBuild2/ANTS-build/ANTsVersionConfig.h:22:9: note: previous definition is here
#define ANTS_VERSION_TWEAK 
        ^
4 warnings generated.
```

I think I can make these go away by just defining default version numbers in `ANTS.cmake`, and not doing the redefinition. Testing now.

**Comment by cookpa** [comment]
I changed the variable name to "ANTS_SNAPSHOT_VERSION" since it could be a release tag rather than a commit hash. 

If no version info is provided at run time or gleaned from a cloned repo, the default version is set to 0.0.0.0 in `ANTS.cmake`. I think this will result in an `ANTsVersionConfig.h` that won't break anything but also doesn't produce any new warnings.

**Comment by gdevenyi** [comment]
Great stuff!

**Pull request merged**
