### PR TITLE
Fix mismatch ambiguous size compilation error

### PR DESCRIPTION
**Pull request by hjmjohnson**
Address compilation issues related to updated version of ITK.

ITK is supporting C++14, and tightening implicit conversion ambiguities.  These changes
affect some coding practices that are not recommended.

### CODE REVIEW

**Comment by ntustison** [comment]
Thank you very much, @hjmjohnson .

**Comment by cookpa** [comment]
The SuperBuild is failing on CircleCI (Ubuntu, GCC 7) and my Mac (Clang 12.0.0). Are there some config options that need to change?

**Comment by ntustison** [comment]
Did you include [this commit](https://github.com/ANTsX/ANTs/commit/078ecf017f051d14c6c5150d6a19dc97e1806de6)?

**Comment by cookpa** [comment]
I didn't see that. Looks good now. Thanks

**Pull request merged**
