### PR TITLE
WIP: Update vtk: InsertNextTypedTuple replaced InsertNextTupleValue 

### PR DESCRIPTION
**Pull request by luzpaz**
per vtk 7.1 updates at https://www.vtk.org/doc/nightly/html/VTK-7-1-Changes.html
Issue #466

### CODE REVIEW

**Comment by gdevenyi** [comment]
If ANTs is getting updated to 8.1.1, should make sure there aren't any other breaking changes...

**Comment by luzpaz** [comment]
@gdevenyi for sure that's why there there's a `WIP` in the title.

**Comment by hjmjohnson** [comment]
@luzpaz @gdevenyi  I should have paid more attention to the open issues.  I did not see that this issue was being addressed already.

**Comment by luzpaz** [comment]
It's not being addressed actively. We're trying to get distros to update to latest vtk which is no small matter as many applications use it as a dependency. So it would be useful if ANTs can consider updating itself to accomodate that or at least patching vtk install. Anyone interested ?

**Comment by luzpaz** [comment]
Vtk 8.2.0 has been released 
https://blog.kitware.com/vtk-8-2-0/
Is this project planning to update the codebase to keep up ?

**Comment by ntustison** [comment]
This was never finished so I'm replacing it with a new pull request.

**Comment by luzpaz** [comment]
bump

**Pull request closed without merging**
