### PR TITLE
ENH: Add Ubuntu 24.04

### PR DESCRIPTION
**Pull request by gdevenyi**
Add 24.04 by copy-paste of the existing GH action.

### CODE REVIEW

**Comment by cookpa** [comment]
Thanks, happy to add this, have you verified that it builds?

**Comment by gdevenyi** [comment]
I was expecting it to build here in the PR, but I guess it won't since its a release-only trigger. I'm trying to figure out how to do it manually on my fork now...

**Comment by cookpa** [comment]
It is annoying and I probably should make a workflow_dispatch option. The way I currently test is to make releases on my fork.

**Comment by cookpa** [comment]
You know, I will just test it, I have it all set up

**Comment by gdevenyi** [comment]
>  The way I currently test is to make releases on my fork.

I figured, I just tried that on my fork and it didn't work for me :-/

**Comment by cookpa** [comment]
Yeah, you have to enable actions, and then disable the ones you don't want...I will fix this because things break on release and it would be good to be able to test

**Comment by gdevenyi** [comment]
How fast are the builds? I was looking at adding this
https://github.com/marketplace/actions/ccache-for-gh-actions

But like this I can't really test it easily...

**Comment by cookpa** [comment]
About an hour. I've used the cache before in python, it can help but caches only last a week so they are good for a nightly build but not really for releases

**Pull request merged**
