### PR TITLE
ENH: Added a new feature to ExtractSliceFromImage

### PR DESCRIPTION
**Pull request by aghayoor**
An optional boolean argument is added to the command line. The default is 0, but if
it is set to 1 by user, the extracted slice will be saved in a blank original space.

Usage:
ExtractSliceFromImage imageDimension inputImage outputSlice direction(e.g. 0, 1, 2) slice_number [KeepSliceInOriginalSpace (0 or 1)]

### CODE REVIEW

**Comment by aghayoor** [comment]
I tested the new functionality on some histology test data, and it worked properly.
Also, the changes are backward compatible. The old command line will work the same as before.

**Comment by ntustison** [comment]
Thanks for this @aghayoor .  As soon as the checks finish, I'll merge this.

**Comment by ntustison** [comment]
I'm going to go ahead and merge this because it's a single program and, from what I can tell, we're still working on @gdevenyi 's refactoring of the travis builds.  We'll address any issues that might arise from this commit once the dust is settled.

**Comment by aghayoor** [comment]
@ntustison : Thank you!

**Pull request merged**
