### PR TITLE
Adapted for Windows

### PR DESCRIPTION
**Pull request by muschellij2**
I think this should be the necessary adaptations for ANTsRCore and Windows.  I think @1alebra2 said that things were too big, so he split them, which I've done in this build.  I'm unsure if this is necessary with `-mbig-obj` flag that I put in the `ANTsRCore` windows branch, but I think it's fine to do this regardless.

If you agree the splitting is fine, then we can incorporate, which is necessary for Windows+ANTsRcore.

### CODE REVIEW

**Comment by 1alebra2** [comment]
the  -mbig-obj switch does not help for the big obj. files. I tried it. I left
it in the compilation to avoid any possible complications. ANTsRTransform.cpp
should be splitted as well, see the src directory, please. 



>>> John Muschelli <notifications@github.com> schrieb am 11.08.2018 um 00:21:
I think this should be the necessary adaptations for ANTsRCore and Windows. I
think @1alebra2
( https://github.com/1alebra2)  said that things were too big, so he split
them, which I've done in this build. I'm unsure if this is necessary with
-mbig-obj flag that I put in the ANTsRCore windows branch, but I think it's
fine to do this regardless.
If you agree the splitting is fine, then we can incorporate, which is
necessary for Windows+ANTsRcore.
You can view, comment on, or merge this pull request online at:
  https://github.com/ANTsX/ANTs/pull/623
Commit Summary 	●  Merging seeing if we can get rid of these
warnings
	●  Merging with Avants
	●  Trying a little windows action
	●  trying appveyor
	●  trying appveyor
	●  needed to fix the .git at the end
	●  trying just for fun
	●  lemme see that PAAATTHHH
	●  lemme see that PAAATTHHH
	●  lemme see that PAAATTHHH after duh
	●  trying matrix
	●  trying matrix
	●  trying matrix
	●  trying matrix
	●  trying matrix
	●  changed order
	●  no matrix yet
	●  one liner
	●  too many cd
	●  turning off examples and testing
	●  msys be damned!
	●  matching the itktag from ITKR
	●  need to change dirs
	●  typo
	●  Trying to track down threads problem
	●  Unsigned int problem with morph_flag
	●  trying to fix iMathFunctions
	●  fixing it back
	●  added extern
	●  doing iMath functions serialized
	●  removing dups of morph_shape
	●  added in imagefilter
	●  updated the hxx imathfunctions
	●  added both func1 and func2 the filters
	●  added cmake_sh to the bool mix
File Changes 	●   M Examples/iMath.cxx
( https://github.com/ANTsX/ANTs/pull/623/files#diff-0)  (2) 
	●   M Examples/iMathFunctions.h
( https://github.com/ANTsX/ANTs/pull/623/files#diff-1)  (129) 
	●   M Examples/iMathFunctions.hxx
( https://github.com/ANTsX/ANTs/pull/623/files#diff-2)  (791) 
	●   A Examples/iMathFunctions1.h
( https://github.com/ANTsX/ANTs/pull/623/files#diff-3)  (141) 
	●   A Examples/iMathFunctions1.hxx
( https://github.com/ANTsX/ANTs/pull/623/files#diff-4)  (662) 
	●   A Examples/iMathFunctions2.h
( https://github.com/ANTsX/ANTs/pull/623/files#diff-5)  (98) 
	●   A Examples/iMathFunctions2.hxx
( https://github.com/ANTsX/ANTs/pull/623/files#diff-6)  (369) 
	●   M SuperBuild.cmake
( https://github.com/ANTsX/ANTs/pull/623/files#diff-7)  (1) 
	●   A appveyor.yml
( https://github.com/ANTsX/ANTs/pull/623/files#diff-8)  (54) 
Patch Links: 	●  https://github.com/ANTsX/ANTs/pull/623.patch
	●  https://github.com/ANTsX/ANTs/pull/623.diff
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
( https://github.com/ANTsX/ANTs/pull/623) , or mute the thread
(

**Comment by muschellij2** [comment]
Hey @stnava - any word on this branch?

**Comment by stnava** [comment]
is this ready to merge?

brian

**Comment by stnava** [comment]
looks innocuous enough - merge 4 windows hordes

**Pull request merged**
