### PR TITLE
Fix some windows compile errors

### PR DESCRIPTION
**Pull request by gdevenyi**
Rebase of #796 so its not a commit on master, and so Travis can test it.

### CODE REVIEW

**Comment by dorianps** [comment]
@gdevenyi I see you posted a fix for Windows. Is ANTs being compiled easily on Windows these days, are you using it there?

**Comment by gdevenyi** [comment]
@dorianps this is simply a rebase of a fix from PR #796 I do not have a way to test it yet, I am exclusively a Linux user.

I hope to get Travis windows working for testing the builds at least.

**Comment by gdevenyi** [comment]
Can someone please restart: https://travis-ci.org/ANTsX/ANTs/jobs/600944447

Also, I'd appreciate a code review here. This looks sensible to me, I did find those functions duplicated elsewhere, and it seems the itksys function is an appropriate thing to use.

**Comment by dorianps** [comment]
Restarted

**Comment by gdevenyi** [comment]
This passes tests and satisfies my sniff test on being okay to do. Ready for merge.

**Comment by ntustison** [comment]
Thanks

**Pull request merged**
