### PR TITLE
Update CMAKE to build static and shared builds properly, fix "make install"

### PR DESCRIPTION
**Pull request by gdevenyi**
Upgrades to the build system in cmake and travis
- update the default flag code from ITK upstream
- Error out for gcc<5 c/o @cookpa 
- Strip out hacky versioning bits to use the lovely git-tag driven versioning
- Fix travis clone so that it gets all tags
- Fix cmake scripts to properly honour CMAKE_INSTALL_PREFIX so that "make install" works
- Set PIC/PIE using canonical cmake method
- Remove hackery for installing scripts to use "make install" infrastructure instead
- use travis-command-wrapper.py for nice travis timeout wrapping

Todo:
- [x] don't install libraries if static build
- [x] don't cpack libraries if static build
- [x] install vtk/itk if shared build
- [x] cpack vtk/itk if shared build
- [ ] ants-config.sh script for setting up environment after https://github.com/BIC-MNI/minc-toolkit-v2/blob/master/minc-toolkit-config.unix.sh.cmake
- [x] audit "make install" for scripts

### CODE REVIEW

**Comment by gdevenyi** [comment]
This is all in prep for making releases on the github release page automatically.

Thing that remains is that when I cpack up a superbuild, I get version 0.1.1 and I can't figure out where thats coming from ... yet.

**Comment by gdevenyi** [comment]
looks like cpack works properly inside ANTs-build directory, which is okay.

I'm going to try to figure out how to skip packaging the libs if a static build is done since they're not needed.

**Comment by gdevenyi** [comment]
Still needed
- what optimisation settings should we use for automated release builds
- should we include debug symbols
- are all scripts listed in Script install list
- what kind of cpack packages would we like to publish
- don't package libraries if static build
- properly install ITK/VTK if shared build
- what compiler version should we use for the official release binaries

**Comment by gdevenyi** [comment]
Fixes #835 #832 #834 #802 #612 #443

**Comment by gdevenyi** [comment]
Needs another kill of existing build if anyone is around

**Comment by ntustison** [comment]
Okay, that should do it.

**Comment by gdevenyi** [comment]
Can someone please kill the running build in favour of the new one waiting? Thanks!

**Comment by ntustison** [comment]
Sure.

**Comment by gdevenyi** [comment]
P.S. If you go to https://travis-ci.org/ANTsX/ANTs/settings there is an "Auto Cancellation" setting, where superseding PR pushes will cancel older ones automatically.

**Comment by ntustison** [comment]
It looks like it's already on.

Screen Shot 2019-09-10 at 9 58 45 AM

**Comment by gdevenyi** [comment]
Ah, more Travis bugs no doubt :-)

**Comment by cookpa** [comment]
Well, it does say "Builds will only be canceled if they are waiting to run, allowing for any running jobs to finish."

**Comment by gdevenyi** [comment]
Ah good catch @cookpa

**Comment by gdevenyi** [comment]
Again if someone wouldn't mind, cancel all but the latest? Thanks :+1:

**Comment by cookpa** [comment]
Done

**Comment by gdevenyi** [comment]
Got it backwards :)
Cancel: https://travis-ci.org/ANTsX/ANTs/builds/583255037
Restart: https://travis-ci.org/ANTsX/ANTs/builds/583258441

**Comment by cookpa** [comment]
OK sorry

**Comment by gdevenyi** [comment]
Morning, could someone please cancel all but the most recent build. Thanks :)

**Comment by ntustison** [comment]
Sure.

**Comment by cookpa** [comment]
@gdevenyi I saw your other closed PR about the gold linker. When adding the GCC version requirement for the ITK build, I found code that checked for the gold linker here

https://github.com/ANTsX/ANTs/blob/47432e61f6a369b3661eb0b4416607f8c8fcb9fa/CMake/ITKSetStandardCompilerFlags.cmake#L274

I removed code that set special conditions for GCC 4.X, which we no longer support. But I don't think you made those same changes when you superseded my PR, so it looks like gold is still not used for the ITK build.

**Comment by gdevenyi** [comment]
Thanks for following up @cookpa , the ITKSetStandardCompilerFlags.cmake is a copy-and-paste from ITK upstream, with a search and replace of ITK with ${PROJECT_NAME} so we can use it in the superbuild.

To my reading, these lines test if gold works, and enable it if so:
https://github.com/gdevenyi/ANTs/blob/cmake-improvements/CMake/ITKSetStandardCompilerFlags.cmake#L269-L274

If you take a look at the current PR build logs, https://travis-ci.org/ANTsX/ANTs/jobs/583679172, and Ctrl-F "have_gold" we see:
```
-- Performing Test have_gold
-- Performing Test have_gold - Success
```

I also see the ``-fuse-ld=gold`` flag being set:
https://travis-ci.org/ANTsX/ANTs/jobs/583679172#L9047

Am I missing something?

**Comment by cookpa** [comment]
No, upon closer inspection I think you are right. Because GCC can no longer be less than 5, the gold failure conditions cannot be true now.

Sent from my iPhone

On Sep 11, 2019, at 12:15 PM, Gabriel A. Devenyi <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for following up @cookpa<https://github.com/cookpa> , the ITKSetStandardCompilerFlags.cmake is a copy-and-paste from ITK upstream, with a search and replace of ITK with ${PROJECT_NAME} so we can use it in the superbuild.

To my reading, these lines test if gold works, and enable it if so:
https://github.com/gdevenyi/ANTs/blob/cmake-improvements/CMake/ITKSetStandardCompilerFlags.cmake#L269-L274

If you take a look at the current PR build logs, https://travis-ci.org/ANTsX/ANTs/jobs/583679172, and Ctrl-F "have_gold" we see:

-- Performing Test have_gold
-- Performing Test have_gold - Success


I also see the -fuse-ld=gold flag being set:
https://travis-ci.org/ANTsX/ANTs/jobs/583679172#L9047

Am I missing something?

**Comment by gdevenyi** [comment]
I've got a lot of changes here, can someone take a look and comment?

Next up is adding the code so that ITK/VTK is installed/cpacked if a SHARED build is made (and not SYSTEM)

**Comment by cookpa** [comment]
@gdevenyi I compiled from the head of your `gdevenyi:cmake-improvements` branch and it compiles with no errors, but I don't see the install directory anywhere. Am I missing something?

**Comment by gdevenyi** [comment]
@cookpa the install target is within ANTS-build, not in the upper level superbuild.

**Comment by cookpa** [comment]
Great, and it copies the script too. Nice!

**Comment by gdevenyi** [comment]
As per comment 1, I still need to add some scripting to install the VTK/ITK libs *if* its a shared build and *if* external stuff is not used.

After that, I need these questions answered:
https://github.com/ANTsX/ANTs/pull/841#issuecomment-529726864

to setup automatic deployment to github releases.

**Comment by gdevenyi** [comment]
Hi, I've run into a bit of a roadblock for the shared build. In this commit: https://github.com/ANTsX/ANTs/pull/841/commits/b45ad316da7a84fd4deaac95fb32da8eacc4af16 I fix the building with shared libraries, however the install command here:
https://github.com/gdevenyi/ANTs/blob/cmake-improvements/Examples/CMakeLists.txt#L55-L62

doesn't result in the ANTS libraries being installed during make install. It looks "right" to me, but cmake is still a bit opaque to me. Everything works as expected if I copy manually and set the LD_LIBRARY_PATH so I know I got the build right, but the install isn't happening.

Can anyone assist?

**Comment by ntustison** [comment]
@hjmjohnson would be the go-to person for this.

**Comment by gdevenyi** [comment]
Hurrah, a green build across the board.

**Comment by ntustison** [comment]
@gdevenyi Great.  So is this ready to merge?

**Comment by gdevenyi** [comment]
@ntustison I'd like to fix the install of the ANTs libraries during shared build as per https://github.com/ANTsX/ANTs/pull/841#issuecomment-533822621 

I'll need to do a bit more experimenting before that.

**Comment by gdevenyi** [comment]
Paging @hjmjohnson, I'm having trouble with "make install" not installing libraries from this snip of code:
https://github.com/gdevenyi/ANTs/blob/cmake-improvements/Examples/CMakeLists.txt#L55-L62

Can you offer any assistance?

**Comment by gdevenyi** [comment]
Success! Somehow I mixed up CMAKE_BUILD_SHARED and BUILD_SHARED_LIBS so the static build macro was always running, hence the proper install wasn't running. Fixes incoming.

I can't help but feel make cmake needs a "strict mode" so I get an error instead of if(CMAKE_BUILD_SHARED) returning FALSE because its non existent.

**Comment by gdevenyi** [comment]
Someone can cancel: https://travis-ci.org/ANTsX/ANTs/builds/590568781

After a green Travis pass this is ready for merge.

This PR fixes "make install" from the ANTs-build directory. It will install libraries if shared, not if static build, including proper logic for the superbuild ITK/VTK. It uses the RPATH feature of linking so that LD_LIBRARY_PATH doesn't need to be adjusted, avoiding conflicts with system libraries. CPack now works as well, which means my next PR will be to add automatic generation of CPACK installation files for tagged releases of ANTs.

**Comment by cookpa** [comment]
> Someone can cancel: https://travis-ci.org/ANTsX/ANTs/builds/590568781

Canceled

**Comment by gdevenyi** [comment]
Travis hiccup, please restart: https://travis-ci.org/ANTsX/ANTs/jobs/590569678

**Comment by gdevenyi** [comment]
All green and ready for merge.

**Comment by gdevenyi** [comment]
I suspect master will need a restart of the build process after at least one failed build to bootstrap the cache.

**Comment by ntustison** [comment]
@gdevenyi Thanks for this.

**Comment by gdevenyi** [comment]
Master could use a restart now to take advantage of the cache now

**Comment by ntustison** [comment]
Quick question---just did a fresh install and now the binaries install to ``${BINARY_DIR}/ANTs-build/Examples/`` which is a change in behavior.  Is this what we want?

**Comment by gdevenyi** [comment]
@ntustison This PR updated the CMAKE so that the build properly honours CMAKE_INSTALL_PREFIX.

The install process is "cmake -DCMAKE_INSTALL_PREFIX=/path/to/install/to; make; cd ANTS-build; make install``

This is to make ANTs conform to how most other software is built and installed (automake, ./configure --prefix=/path/to/install/to; make; make install).

The documentation was already updated: https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

**Comment by ntustison** [comment]
Understood.  But shouldn't the default be to keep the existing behavior?

**Comment by cookpa** [comment]
The existing behavior was to ignore the install prefix, put bin/ inside the build directory and require users to manually copy the scripts, which was not great.

I guess you could make the default prefix ${buildDir}, to get closer to the old behavior.

I fear the "cd ANTs-build" bit is going to become an FAQ. Is there any way to make it work from the superbuild directory, ie the same place that make is called from? Or if not, to print a message telling the user to cd to ANTs-build?

**Comment by gdevenyi** [comment]
> I guess you could make the default prefix ${buildDir}, to get closer to the old behavior.

Just tried that, but with all the manual hackery removed it doesn't work:
```
CMake Error at CMake/PreventInBuildInstalls.cmake:5 (message):
  The current CMAKE_INSTALL_PREFIX points at the build tree:

    /scratch/antsbuild

  This is not supported.
Call Stack (most recent call first):
  Common.cmake:15 (include)
  SuperBuild.cmake:15 (include)
  CMakeLists.txt:67 (include)


-- Configuring incomplete, errors occurred!
```

> I fear the "cd ANTs-build" bit is going to become an FAQ. Is there any way to make it work from the superbuild directory, ie the same place that make is called from? Or if not, to print a message telling the user to cd to ANTs-build?

I agree, I haven't figured that out yet, but I felt this PR was "big enough" to achieve the goal of having a functional STATIC and SHARED build, with working travis and tests. I was hoping a cmake expert like @hjmjohnson might provide an assist eventually..

**Comment by cookpa** [comment]
For my 2c, having to build in ever more diverse environments, VMs and containers, I think a proper make install is a very good thing. Thanks for all your work making it happen.

**Comment by ntustison** [comment]
Agreed.  This is just a rather significant change and so I just want to make sure that we're minimizing the resulting difficulties for us and the users.

**Pull request merged**
