### PR TITLE
Remove manual ccache upgrade as versions suddenly disappear

### PR DESCRIPTION
**Pull request by gdevenyi**

### CODE REVIEW

**Comment by gdevenyi** [comment]
Can someone kick travis to run this build again, I'd like to see if the out-of-time builds can make it with the warm cache.

**Comment by cookpa** [comment]
I can help, if you tell me what to do. I see build #1223 is running.

**Comment by ntustison** [comment]
Yeah, I just restarted it.

**Comment by gdevenyi** [comment]
All good except for two, one always times out, the other, https://travis-ci.org/ANTsX/ANTs/jobs/581363354 can someone restart *just this one* please?

**Comment by cookpa** [comment]
Restarted

**Comment by gdevenyi** [comment]
We look good to go.

**Comment by ntustison** [comment]
Thanks @gdevenyi

**Pull request merged**
